spring:
    application:
        name: spring-project
    datasource:
        url: jdbc:postgresql://db.emzrskxkwaijkriicyox.supabase.co:5432/postgres
        username: postgres
        password: i+*h+En*yci5Xs?
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    server:
        port: 8081
            